# [4.5. Обработка исключений](https://education.yandex.ru/handbook/cpp/article/exceptions)
## A. Адреса
Алексею поручили написать программу, обрабатывающую почтовые адреса.  

Дана структура Address и несколько работающих с ней функций: 

```
#pragma once

#include <string>

struct Address {
    std::string Country;
    std::string City;
    std::string Street;
    std::string House;
};

void Parse(const std::string& line, Address* const address);
void Unify(Address* const address);
std::string Format(const Address& address);
```

Функция Parse принимает на вход текстовую строчку и пытается выделить из неё компоненты адреса.  

Функция Unify пытается привести компоненты адреса к каноническому виду (например, вместо «пр-д Кочновский» записать «Кочновский проезд»).  

Функция Format возвращает текстовое представление адреса.  

Функции Parse и Unify, в духе Google C++ style guide, принимают на вход изменяемые параметры через указатели. Предполагается, что соотвествующие объекты типа Address уже созданы.  

В случае ошибок обработки адреса функции Parse и Unify могут сгенерировать исключения.  

Алексей написал код обработки, но он почему-то не работает:  

```
#include "address.h"
#include <iostream>
#include <string>

int main() {
    std::string line;
    Address* address;
    while (getline(std::cin, line)) {
        Parse(line, address);
        Unify(address);
        std::cout << Format(*address) << "\n";
    }
}
```

Предполагалось, что эта программа будет читать поступающие на вход строки, извлекать из них адреса и печатать их обработанные текстовые представления. В случае исключений при обработке строки программа должна напечатать просто “exception” (с переводом строки) и перейти к обработке следующих строк.  

**Примечание**  
Вам нужно исправить ошибки в коде и сдать его в систему. Код структуры Address и функций переписывать не надо: просто подключите в своей программе заголовочный файл address.h. Утечек памяти в вашей программе быть не должно.  

---
```c++
#include "address.h"
#include <iostream>
#include <string>

int main() {
    std::string line;
    while (getline(std::cin, line)) {
        Address* address = new Address;
        try {
            Parse(line, address);
            Unify(address);
            std::cout << Format(*address) << "\n";
        }
        catch (...) {
            std::cout << "exception\n";
        }
        delete address;
    }
}
```

## B. Retry
Иногда некоторые действия не получается выполнить с первого раза. Например, обращение по сети в сторонний сервис может обернуться неудачей из-за сетевых проблем или перегрузки сервиса. В таких случаях иногда пишут код, который пытается повторить такое действие несколько раз подряд.  

Вам надо написать реализацию функции DoWithRetry с таким заголовком:  

```
#include <exception>
#include <functional>
#include <optional>

template <typename Result, typename Exception = std::exception>
std::optional<Result> DoWithRetry(std::function<Result()> func,
                                  int retryCount, int sleepTime, bool throwLast);
```

Функция принимает на вход другую функцию без аргументов, возвращающую значение типа Result, количество повторов, таймаут между повторами и флажок throwLast.  

Одним из шаблонных параметров функции является тип исключения, на которое функция реагирует. Функция должна вызвать func, и если произошло исключение указанного типа, то вызвать нашу функцию Sleep с параметром sleepTime, а затем повторить попытку (если попытки еще остались). Максимальное количество вызовов func, которое может получиться, равно retryCount + 1. Если на последней попытке происходит исключение указанного типа, и throwLast истинно, этот же объект исключения должен проброситься дальше из функции. Если же throwLast ложно, то надо просто вернуть пустой объект std::optional. Если же вызов func закончился успешно, то надо просто вернуть результат func.  

**Примечание**  
Если исключение произошло на последней попытке, то после неё «спать» не надо.  

---
```c++
#include <exception>
#include <functional>
#include <optional>

template <typename Result, typename Exception = std::exception>
std::optional<Result> DoWithRetry(std::function<Result()> func,
    int retryCount, int sleepTime, bool throwLast) {

    for (int i = 0;  i <= retryCount; ++i)
    {
        try {
            return func();
        }
        catch (Exception) {
            if (retryCount == i) {
                if (throwLast) {
                    throw;
                }
            }
            else {
                Sleep(sleepTime);
            }
        }
    }
    return {};
}
```

## C. BiMap
Все вы знаете контейнер std::map, который сопоставляет уникальным ключам значение. Представим теперь, что мы работаем с данными, у которых бывает два типа ключей. Например, студента можно задать номером студенческого билета или логином в системе. При этом не обязательно заданы оба ключа: например, у студента может ещё не быть логина.  

Вам надо написать класс BiMap, к которому можно обратиться за значением по одному из двух типов ключей. Вот заготовка для вашего класса:  

```
#include <stdexcept>
#include <optional>

template <typename Key1, typename Key2, typename Value>
class BiMap {
public:
    // Вставить значение, указав один или оба ключа.
    // Генерирует исключение std::invalid_argument("some text") в случае,
    // если оба ключа пусты, либо один из ключей уже имеется в хранилище.
    void Insert(const std::optional<Key1>& key1, const std::optional<Key2>& key2, const Value& value);

    // Получить значение по ключу первого типа.
    // Генерирует исключение std::out_of_range("some text")
    // в случае отсутствия ключа (как и функция at в std::map).
    Value& GetByPrimaryKey(const Key1& key);
    const Value& GetByPrimaryKey(const Key1& key) const;

    // Аналогичная функция для ключа второго типа.
    Value& GetBySecondaryKey(const Key2& key);
    const Value& GetBySecondaryKey(const Key2& key) const;
};
```

Функция Insert пытается вставить новое значение в хранилище. Ей могут быть указаны один или оба ключа (поэтому ключи передаются через std::optional). Если оба ключа не заданы, или если один из ключей уже есть в хранилище, функция должна сгенерировать исключение std::invalid_argument с каким-либо текстовым параметром.  

Функции GetByPrimaryKey и GetBySecondaryKey должны вернуть значение по ключу соответствующего типа. Они очень похожи на функцию at в std::map: в случае отстутствия ключа должна генерироваться ошибка std::out_of_range.  

Вот пример тестовой программы, демонстрирующей работу этих функций:  

```
#include "bimap.h"

#include <iostream>
#include <string>

using namespace std;

struct Student {
    string Surname, Name;
};

ostream& operator << (ostream& out, const Student& s) {
    return out << s.Surname << " " << s.Name;
}

int main() {
    BiMap<int, string, Student> bimap;  // студента можно определить либо по номеру, либо по логину
    bimap.Insert(42, {}, {"Ivanov", "Ivan"});
    bimap.Insert({}, "cshse-ami-512", {"Petrov", "Petr"});
    bimap.Insert(13, "cshse-ami-999", {"Fedorov", "Fedor"});

    cout << bimap.GetByPrimaryKey(42) << "\n";  // Ivanov Ivan

    cout << bimap.GetBySecondaryKey("cshse-ami-512") << "\n";  // Petrov Petr

    cout << bimap.GetByPrimaryKey(13) << "\n";  // Fedorov Fedor
    cout << bimap.GetBySecondaryKey("cshse-ami-999") << "\n";  // Fedorov Fedor

    // меняем значение по первичному ключу - по вторичному оно тоже должно измениться
    bimap.GetByPrimaryKey(13).Name = "Oleg";

    cout << bimap.GetByPrimaryKey(13) << "\n";  // Fedorov Oleg
    cout << bimap.GetBySecondaryKey("cshse-ami-999") << "\n";  // Fedorov Oleg
    return 0;
}
```

**Примечание**  
Вы можете воспользоваться контейнером std::map для реализации класса (в частности, можно считать, что на ключах определён operator <).  

Сдайте в систему только код класса BiMap без функции main. Подключите все необходимые для вашей реализации библиотеки.  

---
```c++
#include <map>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>

template <typename Key1, typename Key2, typename Value>
class BiMap {
private:
    std::map<Key1, std::shared_ptr<Value>> m1;
    std::map<Key2, std::shared_ptr<Value>> m2;

public:
    // Вставить значение, указав один или оба ключа.
    // Генерирует исключение std::invalid_argument("some text") в случае,
    // если оба ключа пусты, либо один из ключей уже имеется в хранилище.
    void Insert(const std::optional<Key1>& key1, const std::optional<Key2>& key2, const Value& value) {
        if (!key1 && !key2)
        {
            throw std::invalid_argument("No keys were provided.");
        }

        std::shared_ptr ptr = std::make_shared<Value>(value);

        if (key1 && m1.find(*key1) != m1.end()) {
            throw std::invalid_argument("Key1 already exists.");
        }

        if (key2 && m2.find(*key2) != m2.end()) {
            throw std::invalid_argument("Key2 already exists.");
        }

        if (key1) {
            m1[*key1] = ptr;
        }

        if (key2) {
            m2[*key2] = ptr;
        }

    }

    // Получить значение по ключу первого типа.
    // Генерирует исключение std::out_of_range("some text")
    // в случае отсутствия ключа (как и функция at в std::map).
    Value& GetByPrimaryKey(const Key1& key) {
        if (m1.find(key) == m1.end()) {
            throw std::out_of_range("Key not found");
        }
        return *m1[key];

    }
    const Value& GetByPrimaryKey(const Key1& key) const {
        if (m1.find(key) == m1.end()) {
            throw std::out_of_range("Key not found");
        }
        return *m1[key];
    }

    // Аналогичная функция для ключа второго типа.
    Value& GetBySecondaryKey(const Key2& key) {
        if (m2.find(key) == m2.end()) {
            throw std::out_of_range("Key not found");
        }
        return *m2[key];
    }
    const Value& GetBySecondaryKey(const Key2& key) const {
        if (m2.find(key) == m2.end()) {
            throw std::out_of_range("Key not found");
        }
        return *m2[key];
    }
};
```

## D. LoggerGuard
Вася хочет иметь возможность в конце работы своей функции выводить сообщение, что функция завершила работу. На практике исполнение функции может завершиться разными способами:  

- Может быть несколько операторов return.  

- Может вылететь исключение из какой-нибудь вызываемой функции.  

С учетом этих обстоятельств у Василия получается раздутый код:  

```
#include <iostream>

int Function() {
    int value = 1;
    try {
        value = SomeFunction();
        if (value == 0) {
            std::cout << "Function completed\n";
            return value;
        }

        value = SomeOtherFunction();
        if (value == 0) {
            std::cout << "Function completed\n";
            return value;
        }

        value = FinalFunction();  // might throw an exception
    } catch (...) {
        std::cout << "Function completed\n";
        throw;  // throws the exception further.
    }

    std::cout << "Function completed\n";
    return value;
}
```

Вместо этого Василий хотел бы не заниматься копированием одного и тоже же кода. Помогите Василию и реализуйте класс LoggerGuard, который принимает строку и печатает её во время выхода из функции. С использованием этого класса код Василия станет таким:  

```
#include <iostream>

int Function() {
    LoggerGuard logger("Function completed");

    int value = 1;
    try {
        value = SomeFunction();
        if (value == 0) {
            return value;
        }

        value = SomeOtherFunction();
        if (value == 0) {
            return value;
        }

        value = FinalFunction();  // might throw an exception
    } catch (...) {
        throw;  // throws the exception further.
    }

    return value;
}
```

Класс LoggerGuard должен содержать следующий конструктор:  

```
LoggerGuard(const std::string& message, std::ostream& out = std::cout);
```

Здесь message — сообщение, печатаемое перед выходом из функции, а out — поток, в который надо печатать сообщение. Учтите, что это сообщение не обязано содержать символ перевода строки и вам нужно всегда при выводе самим добавлять \n в конце.  

---
```c++
#include <iostream>
#include <string>

class LoggerGuard {
private:
    std::string Message;
    std::ostream& Out;

public:
	LoggerGuard(const std::string& message, std::ostream& out = std::cout):
        Message(message), Out(out) 
    {
	}

    ~LoggerGuard() {
        Out << Message << '\n';
    }
};
```
